"""Tests for memory_reflect.py — daily reflection pipeline.

PRD-8 Phase 2 WS3 parity tests: prove that swapping the inline
``load_*_file()`` reads + identity-section assembly to the consolidated
``build_identity_payload()`` shim is a behavior-preserving refactor — same
ordering (MEMORY/USER/SOUL/SELF/GOALS), same headers, byte-identical output
for the identity slice of the reflection prompt.

Pattern matches the canonical fixture style at
``tests/test_memory_dream.py:25-65`` — seed ``tmp_path / "TheHomie" / "Memory"``,
NEVER read the real ``vault/memory/`` (sanitizer-denied via
``scripts/sanitize.py:32-39``, non-reproducible, may contain private content).

All tests are pure Python — no LLM calls, no network, no real file system
writes beyond ``tmp_path`` fixtures.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

# Ensure scripts dir is on path (defensive — conftest.py also injects it).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


# =============================================================================
# FIXTURE — minimal vault/memory/ tree under tmp_path
# =============================================================================


@pytest.fixture
def reflect_memory_dir(tmp_path: Path) -> Path:
    """Build a deterministic ``<tmp>/vault/memory/`` tree for reflect tests.

    Five identity files (MEMORY, USER, SOUL, SELF, GOALS) plus a daily/ dir
    so the orient-style discovery does not 500. Each file gets distinct
    sentinel content so byte-equality assertions catch ordering / reading
    bugs immediately.
    """
    memory_dir = tmp_path / "TheHomie" / "Memory"
    memory_dir.mkdir(parents=True)
    (memory_dir / "daily").mkdir()

    (memory_dir / "MEMORY.md").write_text(
        "# MEMORY\n\n## Decisions\n\n- decision A\n- decision B\n",
        encoding="utf-8",
    )
    (memory_dir / "USER.md").write_text(
        "# USER\n\nname: TestUser\nrole: tester\n",
        encoding="utf-8",
    )
    (memory_dir / "SOUL.md").write_text(
        "# SOUL\n\ntone: direct\nstyle: concise\n",
        encoding="utf-8",
    )
    (memory_dir / "SELF.md").write_text(
        "# SELF\n\n## Patterns\n\n- ship cleanly\n",
        encoding="utf-8",
    )
    (memory_dir / "GOALS.md").write_text(
        "# GOALS\n\n## Q2 2026\n\n- finish PRD-8\n",
        encoding="utf-8",
    )
    (memory_dir / "REPOSITORIES.md").write_text(
        "# Repository Index\n\n## Active Repositories\n\n- thehomie\n",
        encoding="utf-8",
    )
    return memory_dir


# =============================================================================
# LEGACY ASSEMBLY — pre-refactor logic, preserved as a private test helper
# =============================================================================


def _legacy_load_current_memory(memory_file: Path) -> str:
    if memory_file.exists():
        return memory_file.read_text(encoding="utf-8")
    return ""


def _legacy_load_user_file(user_file: Path) -> str:
    if user_file.exists():
        return user_file.read_text(encoding="utf-8")
    return ""


def _legacy_load_soul_file(soul_file: Path) -> str:
    if soul_file.exists():
        return soul_file.read_text(encoding="utf-8")
    return ""


def _legacy_load_goals_file(goals_file: Path) -> str:
    if goals_file.exists():
        return goals_file.read_text(encoding="utf-8")
    return ""


def _legacy_load_self_file(self_file: Path) -> str:
    if self_file.exists():
        return self_file.read_text(encoding="utf-8")
    return ""


def _legacy_build_reflect_identity_section(memory_dir: Path) -> str:
    """Pre-refactor identity-section assembly for memory_reflect.py.

    Mirrors the prompt body at memory_reflect.py:202-236 verbatim — same
    ordering (MEMORY/USER/SOUL/SELF/GOALS) and same headers. This helper
    is the parity baseline; behaviour change here = behaviour change in
    production.
    """
    current_memory = _legacy_load_current_memory(memory_dir / "MEMORY.md")
    current_user = _legacy_load_user_file(memory_dir / "USER.md")
    current_soul = _legacy_load_soul_file(memory_dir / "SOUL.md")
    current_goals = _legacy_load_goals_file(memory_dir / "GOALS.md")
    current_self = _legacy_load_self_file(memory_dir / "SELF.md")
    current_repositories = _legacy_load_current_memory(memory_dir / "REPOSITORIES.md")

    return f"""## Current MEMORY.md

{current_memory}

## Current USER.md

{current_user}

## Current SOUL.md

{current_soul}

## Current SELF.md

{current_self}

## Current GOALS.md (read-only context — do NOT edit this file during reflection)

{current_goals}

## Current REPOSITORIES.md (private repo routing context)

{current_repositories}"""


# F2 post-build fix: production helper IS the test target. Drift in the
# production helper now breaks the parity tests immediately — gas-station
# concern (test-local copy of prod assembly) closed.
from memory_reflect import _assemble_reflect_identity_section


# =============================================================================
# PARITY TESTS
# =============================================================================


class TestPromptParityWithShim:
    def test_prompt_parity_with_shim(self, reflect_memory_dir: Path) -> None:
        """Legacy + shim-based identity section are byte-identical.

        WS3 acceptance criterion ``memory_reflect_refactor_parity_preserved``
        (verification: ``pytest tests/test_memory_reflect.py::test_prompt_parity_with_shim``).
        """
        legacy = _legacy_build_reflect_identity_section(reflect_memory_dir)
        new = _assemble_reflect_identity_section(reflect_memory_dir)

        assert legacy == new, (
            "Identity-section parity broken between legacy reads + shim. "
            "Refactor introduced a behavior change. Diff first 200 chars:\n"
            f"  legacy[:200]={legacy[:200]!r}\n"
            f"  new[:200]={new[:200]!r}"
        )

    def test_prompt_parity_with_shim_missing_files(self, tmp_path: Path) -> None:
        """Missing identity files → both paths return empty strings, no exception.

        Validates the fail-open contract: ``read_file_safe`` returns ``""`` and
        the shim's ``payload.get(name, '')`` idiom resolves the same way.
        """
        empty_dir = tmp_path / "TheHomie" / "Memory"
        empty_dir.mkdir(parents=True)

        legacy = _legacy_build_reflect_identity_section(empty_dir)
        new = _assemble_reflect_identity_section(empty_dir)

        assert legacy == new
        # Confirm both paths actually emitted empty content blocks (no crash,
        # no path leakage in the rendered output).
        assert "## Current MEMORY.md\n\n\n\n## Current USER.md" in new
        assert "## Current REPOSITORIES.md (private repo routing context)" in new

    def test_prompt_parity_with_shim_partial_files(self, tmp_path: Path) -> None:
        """Mixed presence (some files exist, some missing) preserves parity."""
        memory_dir = tmp_path / "TheHomie" / "Memory"
        memory_dir.mkdir(parents=True)

        # Only seed MEMORY.md and SELF.md; USER/SOUL/GOALS are absent.
        (memory_dir / "MEMORY.md").write_text(
            "# MEMORY\nentry one\n", encoding="utf-8"
        )
        (memory_dir / "SELF.md").write_text(
            "# SELF\npattern A\n", encoding="utf-8"
        )

        legacy = _legacy_build_reflect_identity_section(memory_dir)
        new = _assemble_reflect_identity_section(memory_dir)

        assert legacy == new
        assert "entry one" in new
        assert "pattern A" in new


# =============================================================================
# WS3 #84 — write-time-contradiction operator-visible count (M3) print path
# =============================================================================
#
# These drive the REAL _run_reflection_inner so the production print line at
# memory_reflect.py:529-539 executes. The line is conditional on the SECOND
# tuple element returned by apply_operator_beliefs (write_time_applied):
#
#     belief_count, write_time_applied = await apply_operator_beliefs(...)
#     if write_time_applied:
#         print(f"... write-time contradictions applied: {write_time_applied}")
#
# A regression that drops the unpack, makes the print unconditional, or stops
# threading the count would flip one of these two tests. All heavy collaborators
# are patched to no-ops and every state/dir constant is redirected to tmp_path
# (the suite NEVER touches real vault/memory/ or live state files).


def _drive_reflection_for_print(
    monkeypatch,
    tmp_path,
    apply_return,
    *,
    crypto_post_step=None,
):
    """Run the REAL _run_reflection_inner with collaborators stubbed + state
    redirected to tmp; return captured stdout. ``apply_return`` is the
    ``(written, write_time_applied)`` tuple the patched apply_operator_beliefs
    yields — the ONLY input that should drive the write-time print."""
    import asyncio

    # Hermetic: no Langfuse export attempt (the local server is intentionally
    # dead; tracing fails open but emits a noisy connection traceback otherwise).
    monkeypatch.setenv("LANGFUSE_ENABLED", "false")

    import memory_reflect as mr
    from cognition import belief_conflicts as bc_mod
    from cognition import operator_beliefs as ob_mod
    from runtime.base import RUNTIME_LANE_CLAUDE_NATIVE, RuntimeResult

    # Redirect every dir/state constant the function touches to tmp_path.
    mem_dir = tmp_path / "TheHomie" / "Memory"
    daily_dir = mem_dir / "daily"
    state_dir = tmp_path / "state"
    daily_dir.mkdir(parents=True)
    state_dir.mkdir(parents=True)
    inf_state = state_dir / "self-model-inferences.json"
    refl_state = state_dir / "reflection-state.json"
    monkeypatch.setattr(mr, "MEMORY_DIR", mem_dir, raising=False)
    monkeypatch.setattr(mr, "DAILY_DIR", daily_dir, raising=False)
    monkeypatch.setattr(mr, "REFLECTION_STATE_FILE", refl_state, raising=False)
    monkeypatch.setattr("config.INFERENCE_STATE_FILE", inf_state, raising=False)

    # One log so the function does NOT early-return at the "no logs" guard.
    monkeypatch.setattr(
        mr, "get_recent_logs", lambda days=1: [("2026-06-21", "did stuff")]
    )

    # The reflection LLM call -> REFLECTION_OK (skips amendment/promotion writes).
    async def _fake_lanes(_req):
        return RuntimeResult(
            text="REFLECTION_OK",
            runtime_lane=RUNTIME_LANE_CLAUDE_NATIVE,
            provider="test",
            model="m",
            cost_usd=0.0,
        )

    monkeypatch.setattr(mr, "run_with_runtime_lanes", _fake_lanes)

    # Act-1 extraction collaborators (lazy-imported from their source modules).
    async def _fake_extract(*_a, **_k):
        return [{"claim": "operator prefers concise answers", "kind": "reflection"}]

    async def _fake_apply(*_a, **_k):
        return apply_return  # (written, write_time_applied) — the print's input

    monkeypatch.setattr(ob_mod, "extract_operator_beliefs", _fake_extract)
    monkeypatch.setattr(ob_mod, "apply_operator_beliefs", _fake_apply)
    monkeypatch.setattr(
        "session.read_operator_user_turns", lambda *_a, **_k: ["turn"], raising=False
    )

    # Neutralize the live Act-2 nightly judge (no provider call in a unit test).
    async def _no_judge(*_a, **_k):
        return []

    monkeypatch.setattr(bc_mod, "judge_contradictions", _no_judge)

    if crypto_post_step is None:
        async def _silent_crypto_post_step():
            return "CRYPTO_PLAYS_SWEEP_SILENT"

        crypto_post_step = _silent_crypto_post_step
    monkeypatch.setattr(mr, "_run_crypto_plays_post_step", crypto_post_step)

    import io
    from contextlib import redirect_stdout

    buf = io.StringIO()
    with redirect_stdout(buf):
        asyncio.run(mr._run_reflection_inner(test_mode=False, days=1))
    return buf.getvalue()


def test_reflect_logs_write_time_count_when_nonzero(monkeypatch, tmp_path):
    """M3: a nonzero write_time_applied -> the operator-visible line fires with
    the exact count (proves the production print is wired to the real return)."""
    out = _drive_reflection_for_print(monkeypatch, tmp_path, apply_return=(4, 3))
    assert "write-time contradictions applied: 3" in out


def test_reflect_omits_write_time_line_when_zero(monkeypatch, tmp_path):
    """Discrimination companion: write_time_applied == 0 -> NO line (the print is
    truly conditional, not unconditional). Guards against an `if True:` regression."""
    out = _drive_reflection_for_print(monkeypatch, tmp_path, apply_return=(4, 0))
    assert "write-time contradictions applied" not in out
