"""Tests for memory_reflect.py — daily reflection pipeline.

PRD-8 Phase 2 WS3 parity tests: prove that swapping the inline
``load_*_file()`` reads + identity-section assembly to the consolidated
``build_identity_payload()`` shim is a behavior-preserving refactor — same
ordering (MEMORY/USER/SOUL/SELF/GOALS), same headers, byte-identical output
for the identity slice of the reflection prompt.

Pattern matches the canonical fixture style at
``tests/test_memory_dream.py:25-65`` — seed ``tmp_path / "TheHomie" / "Memory"``,
NEVER read the real ``vault/memory/`` (sanitizer-denied via
``scripts/sanitize.py:32-39``, non-reproducible, may contain private content).

All tests are pure Python — no LLM calls, no network, no real file system
writes beyond ``tmp_path`` fixtures.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

# Ensure scripts dir is on path (defensive — conftest.py also injects it).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


# =============================================================================
# FIXTURE — minimal vault/memory/ tree under tmp_path
# =============================================================================


@pytest.fixture
def reflect_memory_dir(tmp_path: Path) -> Path:
    """Build a deterministic ``<tmp>/vault/memory/`` tree for reflect tests.

    Five identity files (MEMORY, USER, SOUL, SELF, GOALS) plus a daily/ dir
    so the orient-style discovery does not 500. Each file gets distinct
    sentinel content so byte-equality assertions catch ordering / reading
    bugs immediately.
    """
    memory_dir = tmp_path / "TheHomie" / "Memory"
    memory_dir.mkdir(parents=True)
    (memory_dir / "daily").mkdir()

    (memory_dir / "MEMORY.md").write_text(
        "# MEMORY\n\n## Decisions\n\n- decision A\n- decision B\n",
        encoding="utf-8",
    )
    (memory_dir / "USER.md").write_text(
        "# USER\n\nname: TestUser\nrole: tester\n",
        encoding="utf-8",
    )
    (memory_dir / "SOUL.md").write_text(
        "# SOUL\n\ntone: direct\nstyle: concise\n",
        encoding="utf-8",
    )
    (memory_dir / "SELF.md").write_text(
        "# SELF\n\n## Patterns\n\n- ship cleanly\n",
        encoding="utf-8",
    )
    (memory_dir / "GOALS.md").write_text(
        "# GOALS\n\n## Q2 2026\n\n- finish PRD-8\n",
        encoding="utf-8",
    )
    return memory_dir


# =============================================================================
# LEGACY ASSEMBLY — pre-refactor logic, preserved as a private test helper
# =============================================================================


def _legacy_load_current_memory(memory_file: Path) -> str:
    if memory_file.exists():
        return memory_file.read_text(encoding="utf-8")
    return ""


def _legacy_load_user_file(user_file: Path) -> str:
    if user_file.exists():
        return user_file.read_text(encoding="utf-8")
    return ""


def _legacy_load_soul_file(soul_file: Path) -> str:
    if soul_file.exists():
        return soul_file.read_text(encoding="utf-8")
    return ""


def _legacy_load_goals_file(goals_file: Path) -> str:
    if goals_file.exists():
        return goals_file.read_text(encoding="utf-8")
    return ""


def _legacy_load_self_file(self_file: Path) -> str:
    if self_file.exists():
        return self_file.read_text(encoding="utf-8")
    return ""


def _legacy_build_reflect_identity_section(memory_dir: Path) -> str:
    """Pre-refactor identity-section assembly for memory_reflect.py.

    Mirrors the prompt body at memory_reflect.py:202-236 verbatim — same
    ordering (MEMORY/USER/SOUL/SELF/GOALS) and same headers. This helper
    is the parity baseline; behaviour change here = behaviour change in
    production.
    """
    current_memory = _legacy_load_current_memory(memory_dir / "MEMORY.md")
    current_user = _legacy_load_user_file(memory_dir / "USER.md")
    current_soul = _legacy_load_soul_file(memory_dir / "SOUL.md")
    current_goals = _legacy_load_goals_file(memory_dir / "GOALS.md")
    current_self = _legacy_load_self_file(memory_dir / "SELF.md")

    return f"""## Current MEMORY.md

{current_memory}

## Current USER.md

{current_user}

## Current SOUL.md

{current_soul}

## Current SELF.md

{current_self}

## Current GOALS.md (read-only context — do NOT edit this file during reflection)

{current_goals}"""


# F2 post-build fix: production helper IS the test target. Drift in the
# production helper now breaks the parity tests immediately — gas-station
# concern (test-local copy of prod assembly) closed.
from memory_reflect import _assemble_reflect_identity_section


# =============================================================================
# PARITY TESTS
# =============================================================================


class TestPromptParityWithShim:
    def test_prompt_parity_with_shim(self, reflect_memory_dir: Path) -> None:
        """Legacy + shim-based identity section are byte-identical.

        WS3 acceptance criterion ``memory_reflect_refactor_parity_preserved``
        (verification: ``pytest tests/test_memory_reflect.py::test_prompt_parity_with_shim``).
        """
        legacy = _legacy_build_reflect_identity_section(reflect_memory_dir)
        new = _assemble_reflect_identity_section(reflect_memory_dir)

        assert legacy == new, (
            "Identity-section parity broken between legacy reads + shim. "
            "Refactor introduced a behavior change. Diff first 200 chars:\n"
            f"  legacy[:200]={legacy[:200]!r}\n"
            f"  new[:200]={new[:200]!r}"
        )

    def test_prompt_parity_with_shim_missing_files(self, tmp_path: Path) -> None:
        """Missing identity files → both paths return empty strings, no exception.

        Validates the fail-open contract: ``read_file_safe`` returns ``""`` and
        the shim's ``payload.get(name, '')`` idiom resolves the same way.
        """
        empty_dir = tmp_path / "TheHomie" / "Memory"
        empty_dir.mkdir(parents=True)

        legacy = _legacy_build_reflect_identity_section(empty_dir)
        new = _assemble_reflect_identity_section(empty_dir)

        assert legacy == new
        # Confirm both paths actually emitted empty content blocks (no crash,
        # no path leakage in the rendered output).
        assert "## Current MEMORY.md\n\n\n\n## Current USER.md" in new

    def test_prompt_parity_with_shim_partial_files(self, tmp_path: Path) -> None:
        """Mixed presence (some files exist, some missing) preserves parity."""
        memory_dir = tmp_path / "TheHomie" / "Memory"
        memory_dir.mkdir(parents=True)

        # Only seed MEMORY.md and SELF.md; USER/SOUL/GOALS are absent.
        (memory_dir / "MEMORY.md").write_text(
            "# MEMORY\nentry one\n", encoding="utf-8"
        )
        (memory_dir / "SELF.md").write_text(
            "# SELF\npattern A\n", encoding="utf-8"
        )

        legacy = _legacy_build_reflect_identity_section(memory_dir)
        new = _assemble_reflect_identity_section(memory_dir)

        assert legacy == new
        assert "entry one" in new
        assert "pattern A" in new
